---
title: "Los Angeles Crimes Analysis"
author: "Ahyoung Ju"
date: "2024-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tseries)
library(forecast)
library(sf)
library(dplyr)
library(ggplot2)
```

```{r}
# loading data
crime <- read.csv("/Users/AhyoungJu/Desktop/Portfolio\ Data/LA_Crimes/lacrimes.csv")
head(crime)
```

```{r}
# organizing data
crime$Date.Rptd <- gsub(" 12:00:00 AM", "", crime$Date.Rptd)
crime$DATE.OCC <- gsub(" 12:00:00 AM", "", crime$DATE.OCC)

crime$Date.Rptd <- as.Date(crime$Date.Rptd, format = "%m/%d/%Y")
crime$DATE.OCC <- as.Date(crime$DATE.OCC, format = "%m/%d/%Y")

df <- crime[order(as.Date(crime$DATE.OCC, format = "%m/%d/%Y")),]

head(df)

# dealing with missing values
na_counts <- colSums(is.na(df))
print(na_counts)
```

```{r}
# dropping specified columns that are not useful for the modeling
columns_to_drop <- c("Date.Rptd", "Part.1.2", "Mocodes", "Weapon.Used.Cd", "Crm.Cd.1", "Crm.Cd.2", "Crm.Cd.3", "Crm.Cd.4", "Cross.Street")

df <- df[, !(names(df) %in% columns_to_drop)]
df$Premis.Cd[is.na(df$"Premis.Cd")] <- 0

na_counts <- colSums(is.na(df))
print(na_counts)
```

```{r}
# sex of victims
print(table(df$Vict.Sex))

df$Vict.Sex[df$Vict.Sex %in% c("H", "-")] <- "X"
print(table(df$Vict.Sex))

# age of victims
print(table(df$Vict.Age))

df$Vict.Age[df$Vict.Age < 0] <- 0
print(table(df$Vict.Age))

# descent of victims
print(table(df$Vict.Descent))

df$Vict.Descent[df$Vict.Descent == "-"] <- "X"
print(table(df$Vict.Descent))

str(df)
```

```{r}
# using time series concept to forecasting the total crime count in LA
crime_volume <- df %>%
  group_by(Date = DATE.OCC) %>%
  summarize(crime_count = n())

monthly_crime <- crime_volume %>%
  group_by(Date = format(Date, "%Y-%m")) %>%
  summarize(crime_count = mean(crime_count))

monthly_crime$Date <- as.Date(paste0(monthly_crime$Date, "-01"))

print(monthly_crime)
```

```{r}
crime_trend <- ggplot(monthly_crime, aes(x = Date, y = crime_count)) +
  geom_line(color = "red", size = 1) +
  geom_line(aes(y = mean(crime_count)), linetype = "dashed", color = "blue", size = 1) +
  labs(title = "Los Angeles Monthly Crime Trend 2020-2024",
       x = "Date Crime Occurred",
       y = "Volume of Crime") +
  theme_minimal()

print(crime_trend)
```

```{r}
# converting the index to data type
ts_data <- ts(monthly_crime$crime_count, frequency = 12)

decomposition <- stl(ts_data, s.window = "periodic")

par(mfrow = c(4, 1), mar = c(4, 4, 2, 1), oma = c(0, 0, 2, 0))
plot(ts_data, main = "Original Time Series", ylab = "Crime Count", col = "black")
plot(decomposition$time.series[, "seasonal"], main = "Seasonal Component", ylab = "Seasonal", col = "blue")
plot(decomposition$time.series[, "trend"], main = "Trend Component", ylab = "Trend", col = "red")
plot(decomposition$time.series[, "remainder"], main = "Residuals", ylab = "Residuals", col = "springgreen4")

mtext("Seasonal Decomposition", side = 3, line = 1, outer = TRUE, cex = 1.5)
```

```{r}
periods <- c(1, 2, 3, 4)

differenced_dfs <- lapply(periods, function(period) {
  diff(monthly_crime$crime_count, lag = period)
})

adf_test <- function(series, title = "") {
  cat(sprintf("Augmented Dickey-Fuller Test: %s\n", title))
  result <- adf.test(series, alternative = "stationary")
  cat(sprintf("ADF Test Statistic: %f\n", result$statistic))
  cat(sprintf("p-value: %f\n", result$p.value))
  cat(sprintf("# Lags Used: %d\n", result$lag))
  cat(sprintf("# Observations Used: %d\n", result$nobs))
  
  for (key in names(result$critical)) {
    cat(sprintf("Critical Value (%s): %f\n", key, result$critical[key]))
  }
  
  cat("\n")
}

for (i in seq_along(periods)) {
  adf_test(differenced_dfs[[i]], title = sprintf("Period %d", periods[i]))
}
```

```{r}
train_size <- as.integer(nrow(monthly_crime) * 0.8)

train <- monthly_crime[1:train_size, ]
test <- monthly_crime[(train_size + 1):nrow(monthly_crime), ]

ar_model_train <- arima(train$crime_count, order = c(1, 0, 0))
ma_model_train <- arima(train$crime_count, order = c(0, 0, 1))

ar_predictions <- predict(ar_model_train, n.head = length(test))
ma_predictions <- predict(ma_model_train, n.head = length(test))

print(summary(ar_model_train))
print(summary(ma_model_train))
```